model_list:
  - model_name: qwen3-jordan
    litellm_params:
      model: hosted_vllm/qwen3-1.7b
      api_base: http://vllm:9009/v1
      input_cost_per_token: 0.00000011
      output_cost_per_token: 0.00000126

litellm_settings:
  verbose: False
  modify_params: true
  drop_params: true
  cache: False # Using redis
  general_settings:
    master_key: os.environ/LITELLM_MASTER_KEY
    database_url: postgresql://jordan:16092025dwi@postgredb:5432/litellm
    DISABLE_ADMIN_UI: False
    store_model_in_db: true
