model_list:
  - litellm_params:
      api_base: http://vllm:9009/v1
      input_cost_per_token: 1.1e-07
      model: hosted_vllm/qwen3-1.7b
      output_cost_per_token: 1.26e-06
    model_name: qwen3-jordan

litellm_settings:
  cache: false
  drop_params: true
  modify_params: true
  public_model_groups:
    - qwen3-jordan
  verbose: false

general_settings:
  DISABLE_ADMIN_UI: false
  database_url: os.environ/LITELLM_DB_URI
  master_key: os.environ/LITELLM_MASTER_KEY
  # store_model_in_db: true
  store_prompts_in_spend_logs: true
