[project]
name = "vllm-logger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nvidia-ml-py>=13.590.44",
    "psycopg2-binary>=2.9.11",
]
